/*
 * JS for AreaPanel generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '80456d64-90a3-4e06-9916-7bda187e2d03';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "AreaPanel",
    "location": "AreaPanel.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

AreaPanel_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar_6': 'AreaPanel_mobilenavbar_6',
        'mobilenavbaritem_7': 'AreaPanel_mobilenavbaritem_7',
        'mobilenavbaritem_8': 'AreaPanel_mobilenavbaritem_8',
        'mobilenavbaritem_9': 'AreaPanel_mobilenavbaritem_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 534px;user-zoom: fixed;zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'AreaPanel';

    /*
     * Nonvisual components
     */
    var datasources = [];

    mobilecamera1 = new Apperyio.DataSource(CameraService, {
        'onBeforeSend': function(jqXHR) {

        },
        'onComplete': function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("AreaPanel");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [],
        'requestMapping': [{
            'PATH': ['quality'],
            'TYPE': 'STRING',
            'ATTR': '80'
        }, {
            'PATH': ['destinationType'],
            'TYPE': 'STRING',
            'ATTR': 'Data URL'
        }, {
            'PATH': ['sourcetype'],
            'TYPE': 'STRING',
            'ATTR': 'Camera'
        }, {
            'PATH': ['allowedit'],
            'TYPE': 'STRING',
            'ATTR': 'true'
        }, {
            'PATH': ['encodingType'],
            'TYPE': 'STRING',
            'ATTR': 'JPEG'
        }, {
            'PATH': ['targetWidth'],
            'TYPE': 'STRING',
            'ATTR': '1024'
        }, {
            'PATH': ['targetHeight'],
            'TYPE': 'STRING',
            'ATTR': '768'
        }]
    });

    datasources.push(mobilecamera1);

    /*
     * Events and handlers
     */

    // Before Show
    var AreaPanel_beforeshow = function() {
            Apperyio.CurrentScreen = "AreaPanel";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var AreaPanel_onLoad = function() {
            AreaPanel_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            AreaPanel_deviceEvents();
            AreaPanel_windowEvents();
            AreaPanel_elementsEvents();
        };

    // screen window events
    var AreaPanel_windowEvents = function() {

            $('#AreaPanel').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var AreaPanel_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var AreaPanel_elementsExtraJS = function() {
            // screen (AreaPanel) extra code

        };

    // screen elements handler
    var AreaPanel_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click tap select", '#AreaPanel_mobileheader [name="mobilenavbaritem_8"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        try {
                            mobilecamera1.execute({})
                        } catch (ex) {
                            console.log(ex.name + '  ' + ex.message);
                            hideSpinner();
                        };

                    }
                },
                tap: function() {
                    try {
                        mobilecamera1.execute({})
                    } catch (ex) {
                        console.log(ex.name + '  ' + ex.message);
                        hideSpinner();
                    };
                    event.stopPropagation();
                    return false;
                },
                select: function() {
                    try {
                        mobilecamera1.execute({})
                    } catch (ex) {
                        console.log(ex.name + '  ' + ex.message);
                        hideSpinner();
                    };
                },
            }, '#AreaPanel_mobileheader [name="mobilenavbaritem_8"]');

        };

    $(document).off("pagebeforeshow", "#AreaPanel").on("pagebeforeshow", "#AreaPanel", function(event, ui) {
        AreaPanel_beforeshow();
    });

    if (runBeforeShow) {
        AreaPanel_beforeshow();
    } else {
        AreaPanel_onLoad();
    }
};

$(document).off("pagecreate", "#AreaPanel").on("pagecreate", "#AreaPanel", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    AreaPanel_js();
});