/*
 * JS for Camera generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '80456d64-90a3-4e06-9916-7bda187e2d03';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Map",
    "location": "Map.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Camera",
    "location": "Camera.html"
}];

Camera_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'takephotobutton': 'Camera_takephotobutton',
        'photopreview': 'Camera_photopreview'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 534px;user-zoom: fixed;zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'Camera';

    /*
     * Nonvisual components
     */
    var datasources = [];

    camera_shot = new Apperyio.DataSource(CameraService, {
        'onBeforeSend': function(jqXHR) {

        },
        'onComplete': function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("Camera");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['imageDataBase64'],
            'ID': 'photopreview',
            'ATTR': 'src'
        }],
        'requestMapping': [{
            'PATH': ['quality'],
            'TYPE': 'STRING',
            'ATTR': '80'
        }, {
            'PATH': ['destinationType'],
            'TYPE': 'STRING',
            'ATTR': 'Data URL'
        }, {
            'PATH': ['sourcetype'],
            'TYPE': 'STRING',
            'ATTR': 'Camera'
        }, {
            'PATH': ['allowedit'],
            'TYPE': 'STRING',
            'ATTR': 'true'
        }, {
            'PATH': ['encodingType'],
            'TYPE': 'STRING',
            'ATTR': 'JPEG'
        }, {
            'PATH': ['targetWidth'],
            'TYPE': 'STRING',
            'ATTR': '1024'
        }, {
            'PATH': ['targetHeight'],
            'TYPE': 'STRING',
            'ATTR': '768'
        }]
    });

    datasources.push(camera_shot);

    /*
     * Events and handlers
     */

    // Before Show
    var Camera_beforeshow = function() {
            Apperyio.CurrentScreen = "Camera";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var Camera_onLoad = function() {
            Camera_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            Camera_deviceEvents();
            Camera_windowEvents();
            Camera_elementsEvents();
        };

    // screen window events
    var Camera_windowEvents = function() {

            $('#Camera').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var Camera_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var Camera_elementsExtraJS = function() {
            // screen (Camera) extra code

        };

    // screen elements handler
    var Camera_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#Camera_mobilecontainer [name="takephotobutton"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        try {
                            camera_shot.execute({})
                        } catch (ex) {
                            console.log(ex.name + '  ' + ex.message);
                            hideSpinner();
                        };

                    }
                },
            }, '#Camera_mobilecontainer [name="takephotobutton"]');

        };

    $(document).off("pagebeforeshow", "#Camera").on("pagebeforeshow", "#Camera", function(event, ui) {
        Camera_beforeshow();
    });

    if (runBeforeShow) {
        Camera_beforeshow();
    } else {
        Camera_onLoad();
    }
};

$(document).off("pagecreate", "#Camera").on("pagecreate", "#Camera", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Camera_js();
});